/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.cloumon.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HostHistoryMetrics implements org.apache.thrift.TBase<HostHistoryMetrics, HostHistoryMetrics._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HostHistoryMetrics");

  private static final org.apache.thrift.protocol.TField LOG_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("logTime", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DATAS_FIELD_DESC = new org.apache.thrift.protocol.TField("datas", org.apache.thrift.protocol.TType.LIST, (short)2);

  public String logTime;
  public List<HostHistoryMetricsItem> datas;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOG_TIME((short)1, "logTime"),
    DATAS((short)2, "datas");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOG_TIME
          return LOG_TIME;
        case 2: // DATAS
          return DATAS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOG_TIME, new org.apache.thrift.meta_data.FieldMetaData("logTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DATAS, new org.apache.thrift.meta_data.FieldMetaData("datas", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, HostHistoryMetricsItem.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HostHistoryMetrics.class, metaDataMap);
  }

  public HostHistoryMetrics() {
  }

  public HostHistoryMetrics(
    String logTime,
    List<HostHistoryMetricsItem> datas)
  {
    this();
    this.logTime = logTime;
    this.datas = datas;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HostHistoryMetrics(HostHistoryMetrics other) {
    if (other.isSetLogTime()) {
      this.logTime = other.logTime;
    }
    if (other.isSetDatas()) {
      List<HostHistoryMetricsItem> __this__datas = new ArrayList<HostHistoryMetricsItem>();
      for (HostHistoryMetricsItem other_element : other.datas) {
        __this__datas.add(new HostHistoryMetricsItem(other_element));
      }
      this.datas = __this__datas;
    }
  }

  public HostHistoryMetrics deepCopy() {
    return new HostHistoryMetrics(this);
  }

  @Override
  public void clear() {
    this.logTime = null;
    this.datas = null;
  }

  public String getLogTime() {
    return this.logTime;
  }

  public HostHistoryMetrics setLogTime(String logTime) {
    this.logTime = logTime;
    return this;
  }

  public void unsetLogTime() {
    this.logTime = null;
  }

  /** Returns true if field logTime is set (has been assigned a value) and false otherwise */
  public boolean isSetLogTime() {
    return this.logTime != null;
  }

  public void setLogTimeIsSet(boolean value) {
    if (!value) {
      this.logTime = null;
    }
  }

  public int getDatasSize() {
    return (this.datas == null) ? 0 : this.datas.size();
  }

  public java.util.Iterator<HostHistoryMetricsItem> getDatasIterator() {
    return (this.datas == null) ? null : this.datas.iterator();
  }

  public void addToDatas(HostHistoryMetricsItem elem) {
    if (this.datas == null) {
      this.datas = new ArrayList<HostHistoryMetricsItem>();
    }
    this.datas.add(elem);
  }

  public List<HostHistoryMetricsItem> getDatas() {
    return this.datas;
  }

  public HostHistoryMetrics setDatas(List<HostHistoryMetricsItem> datas) {
    this.datas = datas;
    return this;
  }

  public void unsetDatas() {
    this.datas = null;
  }

  /** Returns true if field datas is set (has been assigned a value) and false otherwise */
  public boolean isSetDatas() {
    return this.datas != null;
  }

  public void setDatasIsSet(boolean value) {
    if (!value) {
      this.datas = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LOG_TIME:
      if (value == null) {
        unsetLogTime();
      } else {
        setLogTime((String)value);
      }
      break;

    case DATAS:
      if (value == null) {
        unsetDatas();
      } else {
        setDatas((List<HostHistoryMetricsItem>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LOG_TIME:
      return getLogTime();

    case DATAS:
      return getDatas();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LOG_TIME:
      return isSetLogTime();
    case DATAS:
      return isSetDatas();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HostHistoryMetrics)
      return this.equals((HostHistoryMetrics)that);
    return false;
  }

  public boolean equals(HostHistoryMetrics that) {
    if (that == null)
      return false;

    boolean this_present_logTime = true && this.isSetLogTime();
    boolean that_present_logTime = true && that.isSetLogTime();
    if (this_present_logTime || that_present_logTime) {
      if (!(this_present_logTime && that_present_logTime))
        return false;
      if (!this.logTime.equals(that.logTime))
        return false;
    }

    boolean this_present_datas = true && this.isSetDatas();
    boolean that_present_datas = true && that.isSetDatas();
    if (this_present_datas || that_present_datas) {
      if (!(this_present_datas && that_present_datas))
        return false;
      if (!this.datas.equals(that.datas))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(HostHistoryMetrics other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    HostHistoryMetrics typedOther = (HostHistoryMetrics)other;

    lastComparison = Boolean.valueOf(isSetLogTime()).compareTo(typedOther.isSetLogTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLogTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.logTime, typedOther.logTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDatas()).compareTo(typedOther.isSetDatas());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDatas()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.datas, typedOther.datas);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // LOG_TIME
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.logTime = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // DATAS
          if (field.type == org.apache.thrift.protocol.TType.LIST) {
            {
              org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
              this.datas = new ArrayList<HostHistoryMetricsItem>(_list0.size);
              for (int _i1 = 0; _i1 < _list0.size; ++_i1)
              {
                HostHistoryMetricsItem _elem2;
                _elem2 = new HostHistoryMetricsItem();
                _elem2.read(iprot);
                this.datas.add(_elem2);
              }
              iprot.readListEnd();
            }
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.logTime != null) {
      oprot.writeFieldBegin(LOG_TIME_FIELD_DESC);
      oprot.writeString(this.logTime);
      oprot.writeFieldEnd();
    }
    if (this.datas != null) {
      oprot.writeFieldBegin(DATAS_FIELD_DESC);
      {
        oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, this.datas.size()));
        for (HostHistoryMetricsItem _iter3 : this.datas)
        {
          _iter3.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HostHistoryMetrics(");
    boolean first = true;

    sb.append("logTime:");
    if (this.logTime == null) {
      sb.append("null");
    } else {
      sb.append(this.logTime);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("datas:");
    if (this.datas == null) {
      sb.append("null");
    } else {
      sb.append(this.datas);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

