/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.cloumon.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HostMonitorItem implements org.apache.thrift.TBase<HostMonitorItem, HostMonitorItem._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HostMonitorItem");

  private static final org.apache.thrift.protocol.TField ITEM_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("itemType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField HOST_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("hostName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField HOST_IP_FIELD_DESC = new org.apache.thrift.protocol.TField("hostIp", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField MONITOR_ITEM_FIELD_DESC = new org.apache.thrift.protocol.TField("monitorItem", org.apache.thrift.protocol.TType.STRUCT, (short)4);

  /**
   * 
   * @see ItemType
   */
  public ItemType itemType;
  public String hostName;
  public String hostIp;
  public MonitorItem monitorItem;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see ItemType
     */
    ITEM_TYPE((short)1, "itemType"),
    HOST_NAME((short)2, "hostName"),
    HOST_IP((short)3, "hostIp"),
    MONITOR_ITEM((short)4, "monitorItem");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ITEM_TYPE
          return ITEM_TYPE;
        case 2: // HOST_NAME
          return HOST_NAME;
        case 3: // HOST_IP
          return HOST_IP;
        case 4: // MONITOR_ITEM
          return MONITOR_ITEM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ITEM_TYPE, new org.apache.thrift.meta_data.FieldMetaData("itemType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ItemType.class)));
    tmpMap.put(_Fields.HOST_NAME, new org.apache.thrift.meta_data.FieldMetaData("hostName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HOST_IP, new org.apache.thrift.meta_data.FieldMetaData("hostIp", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MONITOR_ITEM, new org.apache.thrift.meta_data.FieldMetaData("monitorItem", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MonitorItem.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HostMonitorItem.class, metaDataMap);
  }

  public HostMonitorItem() {
  }

  public HostMonitorItem(
    ItemType itemType,
    String hostName,
    String hostIp,
    MonitorItem monitorItem)
  {
    this();
    this.itemType = itemType;
    this.hostName = hostName;
    this.hostIp = hostIp;
    this.monitorItem = monitorItem;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HostMonitorItem(HostMonitorItem other) {
    if (other.isSetItemType()) {
      this.itemType = other.itemType;
    }
    if (other.isSetHostName()) {
      this.hostName = other.hostName;
    }
    if (other.isSetHostIp()) {
      this.hostIp = other.hostIp;
    }
    if (other.isSetMonitorItem()) {
      this.monitorItem = new MonitorItem(other.monitorItem);
    }
  }

  public HostMonitorItem deepCopy() {
    return new HostMonitorItem(this);
  }

  @Override
  public void clear() {
    this.itemType = null;
    this.hostName = null;
    this.hostIp = null;
    this.monitorItem = null;
  }

  /**
   * 
   * @see ItemType
   */
  public ItemType getItemType() {
    return this.itemType;
  }

  /**
   * 
   * @see ItemType
   */
  public HostMonitorItem setItemType(ItemType itemType) {
    this.itemType = itemType;
    return this;
  }

  public void unsetItemType() {
    this.itemType = null;
  }

  /** Returns true if field itemType is set (has been assigned a value) and false otherwise */
  public boolean isSetItemType() {
    return this.itemType != null;
  }

  public void setItemTypeIsSet(boolean value) {
    if (!value) {
      this.itemType = null;
    }
  }

  public String getHostName() {
    return this.hostName;
  }

  public HostMonitorItem setHostName(String hostName) {
    this.hostName = hostName;
    return this;
  }

  public void unsetHostName() {
    this.hostName = null;
  }

  /** Returns true if field hostName is set (has been assigned a value) and false otherwise */
  public boolean isSetHostName() {
    return this.hostName != null;
  }

  public void setHostNameIsSet(boolean value) {
    if (!value) {
      this.hostName = null;
    }
  }

  public String getHostIp() {
    return this.hostIp;
  }

  public HostMonitorItem setHostIp(String hostIp) {
    this.hostIp = hostIp;
    return this;
  }

  public void unsetHostIp() {
    this.hostIp = null;
  }

  /** Returns true if field hostIp is set (has been assigned a value) and false otherwise */
  public boolean isSetHostIp() {
    return this.hostIp != null;
  }

  public void setHostIpIsSet(boolean value) {
    if (!value) {
      this.hostIp = null;
    }
  }

  public MonitorItem getMonitorItem() {
    return this.monitorItem;
  }

  public HostMonitorItem setMonitorItem(MonitorItem monitorItem) {
    this.monitorItem = monitorItem;
    return this;
  }

  public void unsetMonitorItem() {
    this.monitorItem = null;
  }

  /** Returns true if field monitorItem is set (has been assigned a value) and false otherwise */
  public boolean isSetMonitorItem() {
    return this.monitorItem != null;
  }

  public void setMonitorItemIsSet(boolean value) {
    if (!value) {
      this.monitorItem = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ITEM_TYPE:
      if (value == null) {
        unsetItemType();
      } else {
        setItemType((ItemType)value);
      }
      break;

    case HOST_NAME:
      if (value == null) {
        unsetHostName();
      } else {
        setHostName((String)value);
      }
      break;

    case HOST_IP:
      if (value == null) {
        unsetHostIp();
      } else {
        setHostIp((String)value);
      }
      break;

    case MONITOR_ITEM:
      if (value == null) {
        unsetMonitorItem();
      } else {
        setMonitorItem((MonitorItem)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ITEM_TYPE:
      return getItemType();

    case HOST_NAME:
      return getHostName();

    case HOST_IP:
      return getHostIp();

    case MONITOR_ITEM:
      return getMonitorItem();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ITEM_TYPE:
      return isSetItemType();
    case HOST_NAME:
      return isSetHostName();
    case HOST_IP:
      return isSetHostIp();
    case MONITOR_ITEM:
      return isSetMonitorItem();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HostMonitorItem)
      return this.equals((HostMonitorItem)that);
    return false;
  }

  public boolean equals(HostMonitorItem that) {
    if (that == null)
      return false;

    boolean this_present_itemType = true && this.isSetItemType();
    boolean that_present_itemType = true && that.isSetItemType();
    if (this_present_itemType || that_present_itemType) {
      if (!(this_present_itemType && that_present_itemType))
        return false;
      if (!this.itemType.equals(that.itemType))
        return false;
    }

    boolean this_present_hostName = true && this.isSetHostName();
    boolean that_present_hostName = true && that.isSetHostName();
    if (this_present_hostName || that_present_hostName) {
      if (!(this_present_hostName && that_present_hostName))
        return false;
      if (!this.hostName.equals(that.hostName))
        return false;
    }

    boolean this_present_hostIp = true && this.isSetHostIp();
    boolean that_present_hostIp = true && that.isSetHostIp();
    if (this_present_hostIp || that_present_hostIp) {
      if (!(this_present_hostIp && that_present_hostIp))
        return false;
      if (!this.hostIp.equals(that.hostIp))
        return false;
    }

    boolean this_present_monitorItem = true && this.isSetMonitorItem();
    boolean that_present_monitorItem = true && that.isSetMonitorItem();
    if (this_present_monitorItem || that_present_monitorItem) {
      if (!(this_present_monitorItem && that_present_monitorItem))
        return false;
      if (!this.monitorItem.equals(that.monitorItem))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(HostMonitorItem other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    HostMonitorItem typedOther = (HostMonitorItem)other;

    lastComparison = Boolean.valueOf(isSetItemType()).compareTo(typedOther.isSetItemType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItemType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.itemType, typedOther.itemType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHostName()).compareTo(typedOther.isSetHostName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHostName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostName, typedOther.hostName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHostIp()).compareTo(typedOther.isSetHostIp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHostIp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hostIp, typedOther.hostIp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMonitorItem()).compareTo(typedOther.isSetMonitorItem());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMonitorItem()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.monitorItem, typedOther.monitorItem);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // ITEM_TYPE
          if (field.type == org.apache.thrift.protocol.TType.I32) {
            this.itemType = ItemType.findByValue(iprot.readI32());
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // HOST_NAME
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.hostName = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // HOST_IP
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.hostIp = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // MONITOR_ITEM
          if (field.type == org.apache.thrift.protocol.TType.STRUCT) {
            this.monitorItem = new MonitorItem();
            this.monitorItem.read(iprot);
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.itemType != null) {
      oprot.writeFieldBegin(ITEM_TYPE_FIELD_DESC);
      oprot.writeI32(this.itemType.getValue());
      oprot.writeFieldEnd();
    }
    if (this.hostName != null) {
      oprot.writeFieldBegin(HOST_NAME_FIELD_DESC);
      oprot.writeString(this.hostName);
      oprot.writeFieldEnd();
    }
    if (this.hostIp != null) {
      oprot.writeFieldBegin(HOST_IP_FIELD_DESC);
      oprot.writeString(this.hostIp);
      oprot.writeFieldEnd();
    }
    if (this.monitorItem != null) {
      oprot.writeFieldBegin(MONITOR_ITEM_FIELD_DESC);
      this.monitorItem.write(oprot);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HostMonitorItem(");
    boolean first = true;

    sb.append("itemType:");
    if (this.itemType == null) {
      sb.append("null");
    } else {
      sb.append(this.itemType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("hostName:");
    if (this.hostName == null) {
      sb.append("null");
    } else {
      sb.append(this.hostName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("hostIp:");
    if (this.hostIp == null) {
      sb.append("null");
    } else {
      sb.append(this.hostIp);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("monitorItem:");
    if (this.monitorItem == null) {
      sb.append("null");
    } else {
      sb.append(this.monitorItem);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

