/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.cloumon.thrift;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HostHistoryMetricsItem implements org.apache.thrift.TBase<HostHistoryMetricsItem, HostHistoryMetricsItem._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HostHistoryMetricsItem");

  private static final org.apache.thrift.protocol.TField ITEM_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("itemName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField MONITOR_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("monitorData", org.apache.thrift.protocol.TType.STRING, (short)2);

  public String itemName;
  public String monitorData;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ITEM_NAME((short)1, "itemName"),
    MONITOR_DATA((short)2, "monitorData");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ITEM_NAME
          return ITEM_NAME;
        case 2: // MONITOR_DATA
          return MONITOR_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ITEM_NAME, new org.apache.thrift.meta_data.FieldMetaData("itemName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MONITOR_DATA, new org.apache.thrift.meta_data.FieldMetaData("monitorData", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HostHistoryMetricsItem.class, metaDataMap);
  }

  public HostHistoryMetricsItem() {
  }

  public HostHistoryMetricsItem(
    String itemName,
    String monitorData)
  {
    this();
    this.itemName = itemName;
    this.monitorData = monitorData;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HostHistoryMetricsItem(HostHistoryMetricsItem other) {
    if (other.isSetItemName()) {
      this.itemName = other.itemName;
    }
    if (other.isSetMonitorData()) {
      this.monitorData = other.monitorData;
    }
  }

  public HostHistoryMetricsItem deepCopy() {
    return new HostHistoryMetricsItem(this);
  }

  @Override
  public void clear() {
    this.itemName = null;
    this.monitorData = null;
  }

  public String getItemName() {
    return this.itemName;
  }

  public HostHistoryMetricsItem setItemName(String itemName) {
    this.itemName = itemName;
    return this;
  }

  public void unsetItemName() {
    this.itemName = null;
  }

  /** Returns true if field itemName is set (has been assigned a value) and false otherwise */
  public boolean isSetItemName() {
    return this.itemName != null;
  }

  public void setItemNameIsSet(boolean value) {
    if (!value) {
      this.itemName = null;
    }
  }

  public String getMonitorData() {
    return this.monitorData;
  }

  public HostHistoryMetricsItem setMonitorData(String monitorData) {
    this.monitorData = monitorData;
    return this;
  }

  public void unsetMonitorData() {
    this.monitorData = null;
  }

  /** Returns true if field monitorData is set (has been assigned a value) and false otherwise */
  public boolean isSetMonitorData() {
    return this.monitorData != null;
  }

  public void setMonitorDataIsSet(boolean value) {
    if (!value) {
      this.monitorData = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ITEM_NAME:
      if (value == null) {
        unsetItemName();
      } else {
        setItemName((String)value);
      }
      break;

    case MONITOR_DATA:
      if (value == null) {
        unsetMonitorData();
      } else {
        setMonitorData((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ITEM_NAME:
      return getItemName();

    case MONITOR_DATA:
      return getMonitorData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ITEM_NAME:
      return isSetItemName();
    case MONITOR_DATA:
      return isSetMonitorData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HostHistoryMetricsItem)
      return this.equals((HostHistoryMetricsItem)that);
    return false;
  }

  public boolean equals(HostHistoryMetricsItem that) {
    if (that == null)
      return false;

    boolean this_present_itemName = true && this.isSetItemName();
    boolean that_present_itemName = true && that.isSetItemName();
    if (this_present_itemName || that_present_itemName) {
      if (!(this_present_itemName && that_present_itemName))
        return false;
      if (!this.itemName.equals(that.itemName))
        return false;
    }

    boolean this_present_monitorData = true && this.isSetMonitorData();
    boolean that_present_monitorData = true && that.isSetMonitorData();
    if (this_present_monitorData || that_present_monitorData) {
      if (!(this_present_monitorData && that_present_monitorData))
        return false;
      if (!this.monitorData.equals(that.monitorData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(HostHistoryMetricsItem other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    HostHistoryMetricsItem typedOther = (HostHistoryMetricsItem)other;

    lastComparison = Boolean.valueOf(isSetItemName()).compareTo(typedOther.isSetItemName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetItemName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.itemName, typedOther.itemName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMonitorData()).compareTo(typedOther.isSetMonitorData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMonitorData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.monitorData, typedOther.monitorData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    org.apache.thrift.protocol.TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == org.apache.thrift.protocol.TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // ITEM_NAME
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.itemName = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // MONITOR_DATA
          if (field.type == org.apache.thrift.protocol.TType.STRING) {
            this.monitorData = iprot.readString();
          } else { 
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.itemName != null) {
      oprot.writeFieldBegin(ITEM_NAME_FIELD_DESC);
      oprot.writeString(this.itemName);
      oprot.writeFieldEnd();
    }
    if (this.monitorData != null) {
      oprot.writeFieldBegin(MONITOR_DATA_FIELD_DESC);
      oprot.writeString(this.monitorData);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HostHistoryMetricsItem(");
    boolean first = true;

    sb.append("itemName:");
    if (this.itemName == null) {
      sb.append("null");
    } else {
      sb.append(this.itemName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("monitorData:");
    if (this.monitorData == null) {
      sb.append("null");
    } else {
      sb.append(this.monitorData);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

}

