/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.cloumon.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ItemType implements org.apache.thrift.TEnum {
  DEFAULT(0),
  HOST(1);

  private final int value;

  private ItemType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ItemType findByValue(int value) { 
    switch (value) {
      case 0:
        return DEFAULT;
      case 1:
        return HOST;
      default:
        return null;
    }
  }
}
